---
- name: Install dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - git
  become: true

- name: Ensure local bin directory exists
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'

- name: Install uv
  shell: "curl -LsSf https://astral.sh/uv/install.sh | sh"
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/uv"
